### ISSUE TITLE
Document minimal Lua version required

### ISSUE THREAD

**Issue by severinstrobl** [RRZE-HPC/likwid#324]
Running `likwid-pin` in the latest versions (>5.0) on our CentOS 7.6 system triggers an error
```bash
likwid-pin:283: bad argument #1 to 'match' (string expected, got nil)
```
due to the usage of `%g` in a regular expression. Without any real knowledge of Lua it seems to me that the version 5.1.4 installed on our system simply is too old and does not support this character class. I could not find a definitive list of dependencies, but the [wiki mentions Lua 5.1, 5.2 and 5.3](https://github.com/RRZE-HPC/likwid/wiki/Build), which seems to not be correct any more.

**Comment by TomTheBear** [comment]
We started with Lua 5.2 and with the switch to 5.3, I added `#ifdef LUA_VERSION_NUM == 501` around the problematic statements in the Lua-C-Interface (e.g. https://github.com/RRZE-HPC/likwid/blob/master/src/luawid.c#L1997-L2001). I tried different versions after the changes and had no problem. But that's already some time ago and I might have introduced changes in the Lua scripts which are not compatible to 5.1 anymore. You are right, 5.1 seems not to have `%g` (https://www.lua.org/manual/5.1/manual.html section 5.4.1).

**Comment by severinstrobl** [comment]
Okay, thanks for the clarification.

**Comment by TomTheBear** [comment]
I fixed the problem in likwid-pin with Lua 5.1 (https://github.com/RRZE-HPC/likwid/commit/38ba9704ed90416f3625b850e83534db994c761e). I tested some command lines and didn't find any more Lua-version-clash problems.  Will be in the 5.0.2 release.
The `%g` format does not seem to be a problem. At least it works without complaints.

**Comment by severinstrobl** [comment]
While debugging the initial issue I played around with this section of code and if I remember correctly, using the `%g` in the regex resulted in the match to always fail, i.e., return `nil`. Presumably 38ba970 handles the `nil`, but does not fix the regex failing.

**Comment by TomTheBear** [comment]
That's unfortunate. I tested it and did not see problems because returning `nil` is a common case for this match. I should have checked more carefully. I thought it would throw an exception or similar because `%g` is invalid if really not supported.

**Comment by TomTheBear** [comment]
Since it is no problem in `string.format` to use `%g`, here is a patch for LIKWID 5.0.2 with Lua 5.1 that replaces `%g` with `[^%s]` in `string.match` in `likwid-pin.lua` and `likwid-mpirun.lua`.

```
$ cd likwid-5.0.2
$ patch -p1 < likwid-lua5.1.patch.txt
$ edit config.mk
$ make
```
If it works for you, I'll update the release page and the Spack recipe (Version update PR still open https://github.com/spack/spack/pull/19164).

[likwid-lua5.1.patch.txt](https://github.com/RRZE-HPC/likwid/files/5341379/likwid-lua5.1.patch.txt)
